### ISSUE TITLE
Question regarding trained models?

### ISSUE THREAD

**Issue by xiankgx** [thoppe/instafilter#4]
Dear author, what a smart move to approximate Instagram filters using deep learning! I've done this in the past as a PoC myself. 
My question is are the models well trained? I went to see the samples but a lot of them looked the same without a before and after comparison. Please enlighten me.

**Comment by thoppe** [comment]
Thanks for the kind words! The model is simple, a one-layer fully connected network as it only operates per-pixel. Basically, it's just a map of RGB -> RGB. This means though I can convert the networks from tensorflow to numpy very easily so TF isn't needed.

Because it's pixel based, I only need a single image to train a filter. To do so, I took this image, 

https://github.com/thoppe/instafilter/blob/master/development/examples/Normal.jpg

Which has almost every RGB color in it, ran it through Instagram, then used the resulting image to train, eg.

https://github.com/thoppe/instafilter/blob/master/development/examples/Willow.jpg

Many look similar because the filters themselves are simple on Instagram -- it's looks like some filters just work with a narrow color range or mess with luminosity. Running them on natural images would produce more of an effect.

**Comment by thoppe** [comment]
Feel free to follow me for more projects like these https://twitter.com/metasemantic?lang=en
